### ISSUE TITLE
End-to-end trace breaks on ApiGateway

### ISSUE THREAD

**Issue by DHoefakker** [yantang-msft/service-fabric-application-insights-example#5]
I based my implementation on this example, and it works but not i dont see the complete end to end trace.
There is a difference in my setup (logical ;-)) I have an external facing API. In ApplicationInsights i see 2 traces which are not linked (i see in AI that the operation id's differ).
I created a StackOverflow question, with more detail: https://stackoverflow.com/questions/66011506/applicationinsights-end-2-end-breaks-on-servicefabric-apigateway

I think i need to forward the operation id from the HTTP message (received on the APIGateway) to the SF Remoting requests. But how can i do this ?

**Comment by yantang-msft** [comment]
@DHoefakker This is supposed to happen automatically. I guess you are using an AppInsights version that is using the new [protocol](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#correlation-headers-using-w3c-tracecontext). Unfortunately, this [repo](https://github.com/microsoft/ApplicationInsights-ServiceFabric) is currently in maintenance mode and no new feature will be added.
You can try to raise a question to AppInsights team here: https://github.com/microsoft/ApplicationInsights-dotnet and see it they would plan to support that.
All magic happens here: https://github.com/microsoft/ApplicationInsights-ServiceFabric/tree/master/src/ApplicationInsights.ServiceFabric.Native.Shared, but it's probably not practical to make it work on your own without all the context.
